console: true
# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: library-api
org: mubaraq

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  stage: dev
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:*:*"

functions:
  create:
    handler: handler.create
    events:
      - httpApi:
          path: /books
          method: post
  readAll:
    handler: handler.readAll
    events:
      - httpApi:
          path: /books
          method: get
  readOne:
    handler: handler.readOne
    events:
      - httpApi:
          path: /books/{id}
          method: get
  update:
    handler: handler.update
    events:
      - httpApi:
          path: /books/{id}
          method: put
  delete: 
    handler: handler.delete
    events: 
      - httpApi:
          path: /books/{id}
          method: delete

resources:
  Resources:
    BooksDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: 'books'
plugins:
  - serverless-offline